#! /bin/bash

# password to mailing list
#
# password-to-mailing-list < /etc/passwd
# ypcat passwd | passwd-to-mailing-list
# niscat passwd.org_dir | passwd to mailing list

rm -f /tmp/*.mailing-list

# read
while IFS=: read user passwd uid gid name home Shell
    do
        Shell=${Shell:-/bin/sh} # empty Shell means /bin/ba
        file="/tmp/$(echo $Shell | sed -e 's;^/;;' -e 's;/;-;g').mailing-list"
        echo $user, >> $file
    done
